version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=data-manager-test-access-key
      - MINIO_ROOT_PASSWORD=data-manager-test-secret-key
      - MINIO_DEFAULT_BUCKETS=data-manager-test-bucket
