version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - 127.0.0.1:5432:5432
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
